# Argo CD detects this file and renders the directory with kustomize. It also lets you apply
#   the directory by hand: kubectl apply -k appsets/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-guestbook.yaml
- guestbook-rollout.yaml
